// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use direct connection for migrations (bypasses PgBouncer prepared-statement limitation)
    // DIRECT_URL = postgresql://postgres:PASSWORD@db.PROJECT.supabase.co:5432/postgres
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
